Description: >
  This template illustrates how to use AWS CodeBuild and AWS CodePipeline to
  achieve continuous deployment of source code from a CodeCommit repository via a
  Docker container to a Kubernetes cluster.
Parameters:

  Name:
    Type: String
    Default: codesuite-demo

  TemplateBucket:
    Type: String
    Default: aws-eks-codesuite

  BranchName:
    Type: String
    Default: master

  DeploymentName:
    Type: String
    Default: codesuite-demo

  ClusterName:
    Type: String

Resources:

  LambdaCopy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: {"Fn::Join": ["", ["https://s3.amazonaws.com/", {"Ref": "AWS::AccountId"}, "-", {"Ref": "TemplateBucket"}, "/lambda-copy.yaml"]]}
      Parameters:
        TemplateBucket: {"Fn::Join": ["", [{"Ref": "AWS::AccountId"}, "-", {"Ref": "TemplateBucket"}]]}
        

  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: {"Fn::Join": ["", ["https://s3.amazonaws.com/", {"Ref": "AWS::AccountId"}, "-", {"Ref": "TemplateBucket"}, "/deployment-pipeline.yaml"]]}
      Parameters:
            Name: !Ref AWS::StackName
            TemplateBucket: {"Fn::Join": ["", [{"Ref": "AWS::AccountId"}, "-", {"Ref": "TemplateBucket"}]]}
            BranchName: !Ref BranchName
            DeploymentName: !Ref DeploymentName
            ClusterName: !Ref ClusterName
            LocalBucket: !GetAtt LambdaCopy.Outputs.S3Bucket
